### ISSUE TITLE
Routes with same name may use the wrong handler.

### ISSUE THREAD

**Issue by fidian** [restify/node-restify#1115]
I have been working on automatic route generation using a files in a directory structure in my project, [restify-router-magic](https://github.com/tests-always-included/restify-router-magic).  For instance, you might have `route/index.js` and its contents would look like the below example.  The module also has support for handling named routes by adding a simple "name" property, and that's where this problem starts to rear its ugly head.

```
module.exports = {
    get: function (req, res, next) { ... },
    name: "xyz",
    post: function (req, res, next) { ... }
};
```

My concept of a route is a URI.  It may be parameterized and it may have a query string, but the route is essentially the location of a resource.  I understand "location" to not mean the action, which is the method sent to the resource.  If the HTTP request was "GET /resource", the route is clearly "/resource" and the method is "GET".  This distinction is important to me, especially with the automatic route generation as above.

One adds routes by using `server.get("/resource", function (req, res, next) {...})`.  Named routes will use `{name:"xyz",path:"/resource"}` for the first argument instead.  Please notice that even here the route is separate from the method.  In the 5.x branch's `lib/server.js` and on about line 482, this code exists:

```
if (!opts.name) {
    opts.name = method + '-' + (opts.path || opts.url);

    if (opts.versions.length > 0) {
        opts.name += '-' + opts.versions.join('--');
    }

    opts.name = opts.name.replace(/\W/g, '').toLowerCase();

    if (this.router.mounts[opts.name]) { // GH-401
        opts.name += uuid.v4().substr(0, 7);
    }
}
```

This chunk of code just says to create a name if the route is not named.  There is no "else" path and all named routes are added to the router verbatim using `route.mount()` and that returns `route.name`.  The server will set the chain to `this.routes[route]` and it will be happy to overwrite routes.

So, imagine this sort of thing happening:

```
server.get({name:"xyz", path:"/resource"}, function (req, res, next) {...});
server.post({name:"xyz", path:"/resource"}, function (req, res, next) {...});
```

When web requests come in, the router will find the route and return the name of the route.  The server will look up the chain associated with that route name.  Using code similar to above, this means it will run the POST chain always, never running the GET chain.

I would potentially modify the route names in my module, but then I would have a harder time using named routes when I use `server.router.render()`.

I believe the change should happen in restify.  To implement the change, I see the following tasks:
- Routes need to be looked up for `server.router.render()` and allow the router to map route URIs to names and vice-versa.
- `server.get()` and other method-based functions should not mangle the name.  If there is no name, allow the router to generate one and make sure the method is not included in the name.
- `router.mount()` should not return a name, or it should generate a name in case of conflicts.  An easier approach is to just return an index in an array or a random ID.

**Comment by DonutEspresso** [comment]
Thanks for such a thorough breakdown of the issues here. This is definitely something we'll want to do in upcoming versions. FWIW, some of us are working on something similar over here:

https://github.com/restify/enroute

This looks pretty similar to what you are working on - would love to hear any feedback you might have.

**Comment by fidian** [comment]
I've reviewed several libraries before I wrote one because I don't want to add more code to the world.  However, I would not have chosen `enroute` because it does not appear to meet my needs.

* **Named routes:** Restify supports naming routes, so no matter what the URI is, I am able to refer to it via a hardcoded string.  A magic constant.  This is great for when the API decides to rewire the locations.

* **Routes are defined by files in folders:** I really only wanted to drop in a file to make a new route.  When I drop in a file in addition to updating a configuration file, I feel like that's a failure.

* **Must support factory functions:** I use factories for all of the routes because I am using a dependency injection system.  All of the routes may need to get access to other modules that I have written.  By using a dependency injection system I am able to hugely simplify testing.  I wouldn't force factories upon anyone, but it is nice to have them supported.

I can see how the route files in your library would be what most people would want to use when starting.  One file per route + method combination is appealing.  As system complexity grows, I would imagine that your routes would want to pass most of the work off to managers or services, leaving the route files with a very limited amount of tasks: validate incoming data, pass work off to another library, add links for hypermedia, sometimes convert results (like errors) into more displayable things.  I also am a huge fan of testing, and dislike using modules like [mock-require](https://github.com/boblauer/mock-require) (even though it is AWESOME) to override `require()`.  I don't see any other way to test your route files because they are strongly tied to specific dependencies.

Feel free to email me directly if you'd like more discussions.  I'd prefer to have only relevant comments about the overwriting of route configuration in this issue.

**Comment by DonutEspresso** [comment]
Thank you, that's really great feedback. 👍   Apologies for hijacking the convo, it's something we've been working on the side and I was just curious to get your thoughts given you were working on solving a similar problem. @leitsubomi just a FYI, let's chat offline about this a little later. 

Regarding the main issue, I looked into the router code a bit today (it's a bit dusty in my head). There is definitely a bug for stomping on existing routes. We should fix that.

That said, for your larger problem, if I'm understanding it correctly - there seems to be an impedance mismatch. Fundamentally, restify (and by extension the router) treat the same URL with different methods as independent resources, whereas your approach with configuration aims to combine them under the same resource. Is that accurate? 

I am sure I am simplifying the scenario somewhat, but is it possible to install your routes using a name of your route configuration name + method? i.e., `xyz+GET` or `xyz+ POST`? In other words, if the name is unique, does that solve the problem? If not, what is the remaining gap? I feel like I'm hearing a proposed solution, but I'm not fully grokking your use case. If you're using `router.render` then I suspect something to do with redirection or generating resource URLs using your route configuration objects. If you don't mind, expanding on that a bit might help me understand a little better.

**Comment by fidian** [comment]
If you read the RFC, it is very clear that one URI is one resource.  The method is not a part of the resource, it is instead the action that you are performing on the resource.  I can point you at [several](https://en.wikipedia.org/wiki/Web_resource#Using_HTTP_URIs_to_identify_abstract_resources) [sources](http://martinfowler.com/articles/richardsonMaturityModel.html#level1) that [explain](https://en.wikipedia.org/wiki/HATEOAS#Details) [methods](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html) and [resources](https://tools.ietf.org/html/rfc2616#section-3.2) further.

Additionally, your idea of modifying the name with a GET or POST is technically problematic as well as being semantically broken.  The semantic part is explained in the paragraph above.  The technical problem would show up when people try to use the route.  Here is the code I would use with my route file from the first post.

    // This would fail, even though "xyz" is the name in the route file.
    server.router.render("xyz");

    // People would have to suffix or prefix the names to match
    // whatever the library does.
    server.router.render("xyz-GET");

The disjoint in rendering a route because I have added a method is problematic.  I'd also have to figure out if I wanted the GET or the POST (or any other method) for a route because the library suffixed it with a method.  Routes that I am writing do not necessarily have a GET method, so referring to the route without a method would be the right thing to do.

**Comment by fidian** [comment]
Is it a good idea to automatically close this issue? It's a bug and I'd think fixing bugs should still happen even if the bug is old. If the issue was fixed or bypassed already, then I'm happy with closing this issue.

**Comment by hekike** [comment]
@fidian restify has a completely new router logic in 7.x.
Could you please check out that this issue is also happening with the latest version?

**Comment by fidian** [comment]
I don't think the onus should fall on me for confirming the bug still exists when I had explained how to set up a test to confirm it was broken. It's been a long time and I haven't used `node-restify` since, due to issues with the performance, documentation, and developer responsiveness. Here is something similar, off the top of my head and untested.

```
server.get({name:"xyz", path:"/resource"}, function (req, res, next) {
    res.send("This is GET");
});
server.post({name:"xyz", path:"/resource"}, function (req, res, next) {
    res.send("This is POST");
});
```

With something similar to the above, you should be able to use `curl` and see if the routes work.

**Comment by fidian** [comment]
Ok, I had to make a similar simple example for a reported issue with a library I maintain. This is indeed closed with Restify 7.1.1. :-)

**Comment by hekike** [comment]
@fidian awesome, thanks for checking it out!
